name: "Check docs build"

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Copy requirements
      shell: bash -l {0}
      run: |
        cp requirements.txt docs
        cat requirements-dev.txt >> docs/requirements.txt

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
