name: CI/deploy

# Run on all PR's and on pushes/merges to deploy and master
on:
  pull_request:
  push:
    branches: ['deploy', 'master']

env:
  GITHUB_ACTION_IS_RUNNING: 1
  FLIT_VERSION: "~=3.7"
  DUNAMAI_VERSION: "~=1.12"

jobs:

  tests:
    env:
        PMG_API_KEY: ${{ secrets.PMG_API_KEY }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flit"$FLIT_VERSION"
        pip install dunamai"$DUNAMAI_VERSION"
        flit install --deps=production --extras=test
    - name: Run tests
      run: |
        pytest -v --cov --cov-report xml lightshow/_tests

    # Code coverage when the repo is public
    # - name: Upload code coverage
    #   uses: codecov/codecov-action@v2
    #   timeout-minutes: 10
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     fail_ci_if_error: false

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: "lightshow/ --check"
          fail_on_error: "true"

  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_semantic_version_placeholder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check lines exist
      run: |
        grep -x "__version__ = ...  # semantic-version-placeholder" lightshow/__init__.py

  # TODO: docs builds more than it needs to
  # Refactor the flit install line to just install the --extras=doc
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install flit"$FLIT_VERSION"
        pip install dunamai"$DUNAMAI_VERSION"
        flit install --deps=production --extras=doc
    - name: Build the docs
      run: |
        bash build.sh docs

    #https://coderefinery.github.io/documentation/gh_workflow/
    # - name: Deploy the docs
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.ref == 'refs/heads/deploy'}}
    #   with:
    #     publish_branch: gh-pages
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: docs/build
    #     force_orphan: true

  publish:
    name: Publish to PyPi
    needs: [tests, black, flake8_py3, check_semantic_version_placeholder, docs]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.ref == 'refs/heads/deploy'}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build and publish
      run: | # CHANGE THIS TO USE `bash build.sh publish` LATER!
        echo "PLACEHOLDER!"
      # env:
      #   FLIT_USERNAME: __token__
      #   FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
