name: Docs build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    env:
        PMG_API_KEY: ${{ secrets.PMG_API_KEY }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:

    - uses: actions/checkout@v2

    - name: Install sphinx dependencies
      run: |
        pip install sphinx sphinx_rtd_theme

    - name: Sphinx build
      run: |
        make -C docs/ html
